### ISSUE TITLE
Sort dates by Time

### ISSUE THREAD

**Issue by rstemmer** [rstemmer/WandKalender#1]
Sort the entries of a day be start time

**Comment by rohith-raj-s** [comment]
I can contribute to this issue. Could I get some insight on what's expected?

**Comment by rstemmer** [comment]
Sorry for this very late answer. I'm currently very busy with my paid job :) 

When I tagged this issue with "good first issue", I had in mind that it is necessary to go the whole dataflow from getting the data until rendering it. This gives a good overview of the not yet documented architecture. After solving this issue, you know enough of the code to shape it as you want - to make it your own project.
The first challenge of this issue would have been to answer your questing yourself. Obviously there is no documentation yet, and this project is in an very early state. There is not even an installation instruction.
The issue is, that when there are two event on the same day, one at 10am, one at 11am, and the 11am date has been created before the 10am date, they are listed in the wrong order. So the events are sorted by creating date, not when they actually start.
Usually you want to have the early events listed before the later event.

I'm addressed this issue by myself while I am fixing another bug.

Anyway, thank you very much for the interest.

**Comment by rstemmer** [comment]
Fixed in the backend
